version: "3"

services:
  db:
    image: mysql
    container_name: mysql_ldb
    environment:
      MYSQL_ROOT_PASSWORD: qwerty
      MYSQL_DATABASE: app_db
      MYSQL_USER: sa
      MYSQL_PASSWORD: qwerty
    ports:
      - "6033:3306"
    volumes:
      - ./data/db:/var/lib/mysql
volumes:
  dbdata:
